In [2]:
import numpy as np
arr1 = np.array([1,2,3,4])
print(arr1)

[1 2 3 4]


In [3]:
arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [4]:
my_array = np.full((3,3),5)
print(my_array)
print("list: ",my_array.shape)

[[5 5 5]
 [5 5 5]
 [5 5 5]]
list:  (3, 3)


In [6]:
import numpy as np
arr = np.array([10, 20, 30, 40, 50])

print(arr[1:4])
print(arr[:3])   # Shuru se 3 tak -> [10 20 30] [cite: 148, 150]
print(arr[::2])

[20 30 40]
[10 20 30]
[10 30 50]


In [8]:
a = np.array([1, 2, 3, 4, 5, 6])
mask = a % 2 == 0
print(mask)
print(a[mask])

[False  True False  True False  True]
[2 4 6]


In [4]:
# Ek 2x3 matrix (2 rows, 3 columns)
data = np.array([
    [10, 20, 30],
    [5,  5,  5]
])

# Task: Har column ka maximum number nikalo (Axis 0)
max_vals = np.max(data, axis=0)
print(max_vals)

[10 20 30]


In [7]:
data = np.array([
    [10, 20, 30],
    [40, 50, 60]
])

# Column ka Mean (Average) nikalo
mean = data.mean(axis=0) 
print("Mean:", mean)

# Pure data me se mean ko minus karo (Broadcasting)
centered_data = data - mean
print("Centered Data:\n", centered_data)

Mean: [25. 35. 45.]
Centered Data:
 [[-15. -15. -15.]
 [ 15.  15.  15.]]
